#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=sportbukkit.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "https://repo.oc.tc/content/groups/public/tc/oc/sportbukkit/1.8-R0.1-SNAPSHOT/sportbukkit-1.8-R0.1-20150530.105731-35.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

